# Generated by Django 3.2.7 on 2021-11-29 06:25

import backend.models
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('Cimage', models.ImageField(upload_to=backend.models.Canvas.upload_to)),
                ('canvasRectPoints', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outputImage', models.ImageField(upload_to=backend.models.Image.upload_to)),
                ('points', jsonfield.fields.JSONField(null=True)),
                ('t', models.IntegerField()),
            ],
        ),
    ]
