# Generated by Django 3.2.7 on 2021-11-29 06:34

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='outputImage',
            field=models.ImageField(null=True, upload_to=backend.models.Image.upload_to),
        ),
    ]
