# Generated by Django 3.2.7 on 2021-11-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_image_outputimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
