# Generated by Django 3.2.7 on 2021-11-29 06:42

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_image_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='outputImage',
            field=models.ImageField(default=1, upload_to=backend.models.Image.upload_to),
            preserve_default=False,
        ),
    ]
