# Generated by Django 3.2.7 on 2021-11-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_image_outputimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='op',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
